services:
  # Redis Master
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis_password
    networks:
      - redis-sentinel

  # Redis Replica 1
  redis-replica-1:
    image: redis:7-alpine
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    command: >
      redis-server
      --replicaof redis-master 6379
      --masterauth redis_password
      --requirepass redis_password
      --appendonly yes
    depends_on:
      - redis-master
    networks:
      - redis-sentinel

  # Redis Replica 2
  redis-replica-2:
    image: redis:7-alpine
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    command: >
      redis-server
      --replicaof redis-master 6379
      --masterauth redis_password
      --requirepass redis_password
      --appendonly yes
    depends_on:
      - redis-master
    networks:
      - redis-sentinel

  # Sentinel 1
  sentinel-1:
    image: redis:7-alpine
    container_name: sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel-1:/data
    command: |
      sh -c 'echo "port 26379" > /etc/redis-sentinel.conf &&
             echo "dir /data" >> /etc/redis-sentinel.conf &&
             echo "sentinel monitor mymaster redis-master 6379 2" >> /etc/redis-sentinel.conf &&
             echo "sentinel auth-pass mymaster redis_password" >> /etc/redis-sentinel.conf &&
             echo "sentinel down-after-milliseconds mymaster 5000" >> /etc/redis-sentinel.conf &&
             echo "sentinel parallel-syncs mymaster 1" >> /etc/redis-sentinel.conf &&
             echo "sentinel failover-timeout mymaster 10000" >> /etc/redis-sentinel.conf &&
             echo "logfile /data/sentinel.log" >> /etc/redis-sentinel.conf &&
             redis-sentinel /etc/redis-sentinel.conf'
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis-sentinel

  # Sentinel 2
  sentinel-2:
    image: redis:7-alpine
    container_name: sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel-2:/data
    command: |
      sh -c 'echo "port 26379" > /etc/redis-sentinel.conf &&
             echo "dir /data" >> /etc/redis-sentinel.conf &&
             echo "sentinel monitor mymaster redis-master 6379 2" >> /etc/redis-sentinel.conf &&
             echo "sentinel auth-pass mymaster redis_password" >> /etc/redis-sentinel.conf &&
             echo "sentinel down-after-milliseconds mymaster 5000" >> /etc/redis-sentinel.conf &&
             echo "sentinel parallel-syncs mymaster 1" >> /etc/redis-sentinel.conf &&
             echo "sentinel failover-timeout mymaster 10000" >> /etc/redis-sentinel.conf &&
             echo "logfile /data/sentinel.log" >> /etc/redis-sentinel.conf &&
             redis-sentinel /etc/redis-sentinel.conf'
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis-sentinel

  # Sentinel 3
  sentinel-3:
    image: redis:7-alpine
    container_name: sentinel-3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel-3:/data
    command: |
      sh -c 'echo "port 26379" > /etc/redis-sentinel.conf &&
             echo "dir /data" >> /etc/redis-sentinel.conf &&
             echo "sentinel monitor mymaster redis-master 6379 2" >> /etc/redis-sentinel.conf &&
             echo "sentinel auth-pass mymaster redis_password" >> /etc/redis-sentinel.conf &&
             echo "sentinel down-after-milliseconds mymaster 5000" >> /etc/redis-sentinel.conf &&
             echo "sentinel parallel-syncs mymaster 1" >> /etc/redis-sentinel.conf &&
             echo "sentinel failover-timeout mymaster 10000" >> /etc/redis-sentinel.conf &&
             echo "logfile /data/sentinel.log" >> /etc/redis-sentinel.conf &&
             redis-sentinel /etc/redis-sentinel.conf'
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis-sentinel

networks:
  redis-sentinel:
    driver: bridge

# Usage:
# Start: docker-compose -f docker-compose.sentinel.yml up -d
# Stop: docker-compose -f docker-compose.sentinel.yml down
# Logs: docker-compose -f docker-compose.sentinel.yml logs -f
# Test failover: docker-compose -f docker-compose.sentinel.yml stop redis-master